"""Strategy parameter optimizer — maximises live trading profit.

Usage (from trading_bot/ directory):
    python optimize_strategy.py
    python optimize_strategy.py --days 60 --tickers NVDA TSLA AAPL MSFT AMD
    python optimize_strategy.py --objective ev_per_trade
    python optimize_strategy.py --no-validate        # full-window (overfits)

Two-phase grid search:
  Phase 1 (thresholds): Grid over LONG_THRESHOLD × SHORT_THRESHOLD.
  Phase 2 (atr):        Grid over ATR_STOP_MULTIPLE × ATR_TARGET_MULTIPLE
                        using the best thresholds found in Phase 1.

Walk-forward validation (default ON): each combo is TUNED on the first 70% of the
window and RANKED by its objective on the held-out last 30%. This is the honest
estimate of live performance — picking params by in-sample profit alone overfits
and loses money live. The report flags any set whose OOS profit collapses vs
in-sample.

Objective (default total_pnl = raw trading profit; also ev_per_trade /
profit_factor / sharpe). Bars are fetched ONCE and reused across all combos.

Results written to optimization_results.json.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import sys
from copy import deepcopy
from dataclasses import asdict
from datetime import datetime, timedelta, timezone
from itertools import product
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

_here = Path(__file__).parent
for _candidate in [
    _here / ".env",
    _here.parent / ".env",
    _here.parent / ".env.local",
    _here.parent / "trading-dashboard" / ".env.local",
]:
    if _candidate.exists():
        load_dotenv(_candidate, override=False)

import numpy as np
import pandas as pd

sys.path.insert(0, str(_here))

from config.settings import load_settings, Settings, AgentWeights, RiskConfig, DecisionThresholds
from core.enums import Decision
from core.trade_stats import load_closed_trades, summarize, format_block
from core.paths import volume_dir
from backtest_30day import (
    fetch_bars_range,
    backtest_ticker,
    calc_summary,
    SLIPPAGE_PCT,
    LOOKBACK_BARS,
)
from bootstrap import build_manager

logging.basicConfig(
    level=logging.WARNING,           # suppress agent noise during grid search
    format="%(asctime)s %(levelname)s | %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("opt")
logging.getLogger("opt").setLevel(logging.INFO)

_OUT_DIR       = volume_dir() or _here.parent
RESULTS_FILE   = _OUT_DIR / "optimization_results.json"
# Dashboard files — the existing /backtest "Optimizer Run" panel + config box read these.
OPTIMAL_JSON   = _OUT_DIR / "backtest_optimal.json"
OPTIMAL_CONFIG = _OUT_DIR / "OPTIMAL_CONFIG.txt"
MIN_TRADES     = 20   # min in-sample trades (statistical significance)
MIN_OOS_TRADES = 6    # min out-of-sample trades to trust the validation number
SPLIT_FRAC     = 0.70 # walk-forward: tune on first 70%, validate on last 30%

# Objectives — all "higher is better". Default: total realized P&L (raw trading profit).
OBJECTIVES = ("total_pnl", "ev_per_trade", "profit_factor", "sharpe")
_WORST     = float("-inf")

# Metrics kept per split in the results file / tables (drop the heavy trades list).
_SLIM_KEYS = ("total_trades", "win_rate", "total_pnl", "avg_win", "avg_loss",
              "ev_per_trade", "sharpe", "profit_factor", "max_drawdown")


def _slim(summary: dict) -> dict:
    return {k: summary.get(k) for k in _SLIM_KEYS}


def _write_dashboard_files(best: dict, days: int, objective: str, validated: bool) -> None:
    """Write backtest_optimal.json + OPTIMAL_CONFIG.txt so the dashboard's
    'Optimizer Run' panel and config box populate. Reports the held-out (OOS)
    metrics when validation ran — the honest estimate of live performance."""
    if not best:
        return
    p = best.get("params", {})
    m = best.get("oos") if "oos" in best else best
    payload = {
        "total_trades":  m.get("total_trades", 0),
        "win_rate":      m.get("win_rate", 0.0),
        "total_pnl":     m.get("total_pnl", 0.0),
        "avg_win":       m.get("avg_win", 0.0),
        "avg_loss":      m.get("avg_loss", 0.0),
        "profit_factor": m.get("profit_factor", 0.0),
        "sharpe":        m.get("sharpe", 0.0),
        "max_drawdown":  m.get("max_drawdown", 0.0),
        "ev_per_trade":  m.get("ev_per_trade", 0.0),
        "by_ticker":     [],
        "optimal_params":      {k: float(v) for k, v in p.items()},
        "optimal_window_days": days,
    }
    OPTIMAL_JSON.write_text(json.dumps(payload, indent=2))

    lines = [
        f"# Generated by optimize_strategy.py — {datetime.utcnow().isoformat()}Z",
        f"# Objective: {objective}  ({'walk-forward OOS' if validated else 'full-window'})  Window: {days}d",
        f"# Result: PnL=${payload['total_pnl']:.0f}  WinRate={payload['win_rate']:.1f}%  "
        f"Sharpe={payload['sharpe']:.2f}  Trades={payload['total_trades']}",
        "",
        *[f"{k}={v}" for k, v in p.items()],
    ]
    OPTIMAL_CONFIG.write_text("\n".join(lines) + "\n")

# ── Parameter grids ────────────────────────────────────────────────────────────

THRESHOLD_GRID = {
    "LONG_THRESHOLD":  [55.0, 58.0, 60.0, 63.0, 66.0],
    "SHORT_THRESHOLD": [34.0, 37.0, 40.0, 43.0, 46.0],
}

ATR_GRID = {
    "ATR_STOP_MULTIPLE":   [1.5, 2.0, 2.5, 3.0],
    "ATR_TARGET_MULTIPLE": [2.5, 3.0, 4.0, 5.0],
}

DEFAULT_TICKERS = ["NVDA", "TSLA", "AAPL", "MSFT", "AMD", "META", "AMZN"]


# ── Settings factory ───────────────────────────────────────────────────────────

def _make_settings(overrides: dict) -> Settings:
    """Clone current settings with env var overrides applied."""
    for k, v in overrides.items():
        os.environ[k] = str(v)
    s = load_settings()
    # Clean up so next call starts fresh
    for k in overrides:
        os.environ.pop(k, None)
    return s


# ── Single-combo evaluator ─────────────────────────────────────────────────────

async def _eval_combo(
    params: dict,
    tickers: list[str],
    bars_cache: dict[str, pd.DataFrame],
    spy_bars: Optional[pd.DataFrame],
    use_llm: bool = False,
) -> dict:
    """Run the full backtest for one parameter combination; return summary dict.

    Wires the full agent set (Technical, Fundamental, Risk, Liquid + Insider/
    Squeeze/Macro). The point-in-time agents self-neutralise via ctx.backtest_mode
    (set inside backtest_ticker) so they add no look-ahead bias. The LLM Decision
    agent is deliberately OFF: it picks direction itself and bypasses the
    LONG/SHORT thresholds — the very parameters this optimizer is tuning.
    """
    settings = _make_settings(params)
    pm = build_manager(
        settings,
        broker=None,
        include_live_only_agents=True,
        include_vision=use_llm,
        include_decision_agent=False,
        include_insider=True,
        include_squeeze=True,
    )

    all_trades = []
    for ticker in tickers:
        bars = bars_cache.get(ticker)
        if bars is None or bars.empty:
            continue
        try:
            trades = await backtest_ticker(pm, ticker, bars, spy_bars)
            all_trades.extend(trades)
        except Exception as exc:
            logger.warning("backtest_ticker error %s: %s", ticker, exc)

    summary = calc_summary(all_trades)
    summary["params"] = params
    return summary


# ── Data fetch ─────────────────────────────────────────────────────────────────

async def _fetch_all(
    tickers: list[str],
    days: int,
    key_id: str,
    secret: str,
) -> tuple[dict[str, pd.DataFrame], Optional[pd.DataFrame]]:
    end_dt   = datetime.now(tz=timezone.utc).replace(hour=23, minute=59, second=59)
    start_dt = end_dt - timedelta(days=days + 5)

    all_syms = list(set(tickers + ["SPY"]))
    logger.info("Fetching bars for: %s  (%d days)", all_syms, days)

    tasks = {
        sym: fetch_bars_range(sym, start_dt, end_dt, key_id, secret)
        for sym in all_syms
    }
    results = await asyncio.gather(*tasks.values(), return_exceptions=True)
    bars_map: dict[str, pd.DataFrame] = {}
    for sym, res in zip(tasks.keys(), results):
        if isinstance(res, Exception):
            logger.warning("Fetch error %s: %s", sym, res)
        elif res is not None:
            bars_map[sym] = res

    spy_bars = bars_map.pop("SPY", None)
    return bars_map, spy_bars


# ── Walk-forward split ─────────────────────────────────────────────────────────

def _split_caches(bars_cache: dict, frac: float) -> tuple[dict, dict]:
    """Split each ticker's bars by time: first `frac` = in-sample, rest = OOS.

    The OOS slice keeps LOOKBACK_BARS of history before the split so the first
    out-of-sample evaluation still has its full agent lookback window (and no
    in-sample trade is double-counted — trades are only opened from bar
    LOOKBACK_BARS onward, which for OOS is exactly the split point).
    """
    is_cache, oos_cache = {}, {}
    for tk, bars in bars_cache.items():
        n = len(bars)
        split = int(n * frac)
        if split <= LOOKBACK_BARS or (n - split) <= LOOKBACK_BARS:
            # Not enough data to form both halves with a full lookback — keep
            # it whole in the in-sample set so it still contributes there.
            is_cache[tk] = bars
            continue
        is_cache[tk]  = bars.iloc[:split]
        oos_cache[tk] = bars.iloc[split - LOOKBACK_BARS:]
    return is_cache, oos_cache


# ── Combo evaluation (in-sample + optional OOS) ────────────────────────────────

async def _evaluate(
    params: dict,
    tickers: list[str],
    spy_bars,
    *,
    objective: str,
    use_llm: bool,
    is_cache: dict,
    oos_cache: Optional[dict],
) -> dict:
    """Evaluate one param set. Returns a record with a `rank_value` for sorting.

    When `oos_cache` is provided (walk-forward mode) the record is ranked by the
    objective measured on the HELD-OUT data — the honest estimate of live profit.
    Otherwise it's ranked on the full-window in-sample number.
    """
    is_sum = await _eval_combo(params, tickers, is_cache, spy_bars, use_llm)

    if oos_cache is None:
        rec = dict(is_sum)
        rec["params"]     = params
        rec["rank_value"] = is_sum.get(objective, _WORST) or _WORST
        rec["trades_ok"]  = is_sum.get("total_trades", 0) >= MIN_TRADES
        return rec

    oos_sum = await _eval_combo(params, tickers, oos_cache, spy_bars, use_llm)
    rec = {
        "params":     params,
        "in_sample":  _slim(is_sum),
        "oos":        _slim(oos_sum),
        "rank_value": oos_sum.get(objective, _WORST) or _WORST,
        "trades_ok": (is_sum.get("total_trades", 0)  >= MIN_TRADES and
                      oos_sum.get("total_trades", 0) >= MIN_OOS_TRADES),
    }
    return rec


# ── Grid runners ───────────────────────────────────────────────────────────────

async def _run_grid(
    label: str,
    combos: list[dict],
    tickers: list[str],
    spy_bars,
    *,
    objective: str,
    use_llm: bool,
    is_cache: dict,
    oos_cache: Optional[dict],
) -> list[dict]:
    logger.info("%s: %d combos (objective=%s, %s)",
                label, len(combos), objective,
                "walk-forward OOS" if oos_cache is not None else "full-window")
    import time as _time_mod
    results = []
    _g_start = _time_mod.monotonic()
    for i, params in enumerate(combos, 1):
        rec = await _evaluate(params, tickers, spy_bars, objective=objective,
                              use_llm=use_llm, is_cache=is_cache, oos_cache=oos_cache)
        elapsed = _time_mod.monotonic() - _g_start
        eta     = int(elapsed / i * (len(combos) - i)) if i else 0
        logger.info("PROGRESS: %d/%d (%.0f%%) ETA: %ds | %s %s",
                    i, len(combos), 100 * i / len(combos), eta,
                    label, _fmt_params(params))
        if rec["trades_ok"]:
            results.append(rec)
        else:
            logger.debug("    → skipped (too few trades)")
    return sorted(results, key=lambda r: r["rank_value"], reverse=True)


def _threshold_combos(atr_stop: float, atr_target: float) -> list[dict]:
    keys   = list(THRESHOLD_GRID.keys())
    combos = [dict(zip(keys, v)) for v in product(*THRESHOLD_GRID.values())]
    combos = [c for c in combos if c["LONG_THRESHOLD"] - c["SHORT_THRESHOLD"] >= 10]
    return [{**c, "ATR_STOP_MULTIPLE": atr_stop, "ATR_TARGET_MULTIPLE": atr_target}
            for c in combos]


def _atr_combos(long_thresh: float, short_thresh: float) -> list[dict]:
    keys   = list(ATR_GRID.keys())
    combos = [dict(zip(keys, v)) for v in product(*ATR_GRID.values())]
    combos = [c for c in combos if c["ATR_TARGET_MULTIPLE"] > c["ATR_STOP_MULTIPLE"]]
    return [{**c, "LONG_THRESHOLD": long_thresh, "SHORT_THRESHOLD": short_thresh}
            for c in combos]


# ── Output helpers ─────────────────────────────────────────────────────────────

def _fmt_params(p: dict) -> str:
    return "  ".join(f"{k}={v}" for k, v in p.items())


def _params_label(p: dict) -> str:
    return "  ".join(f"{k.replace('_THRESHOLD','_T').replace('_MULTIPLE','_M')}={v}"
                     for k, v in p.items())


def _print_table(results: list[dict], title: str, objective: str) -> None:
    if not results:
        print(f"\n  {title}: no results met the minimum trade threshold.\n")
        return

    validated = "oos" in results[0]
    print(f"\n{'=' * 92}")
    print(f"  {title}  (ranked by {'OOS ' if validated else ''}{objective})")
    print(f"{'=' * 92}")

    if validated:
        print(f"  {'Params':<40} {'IS_PnL':>9} {'OOS_PnL':>9} {'OOS_Tr':>6} "
              f"{'OOS_Win':>7} {'OOS_EV/T':>8} {'OOS_Sh':>7}")
        print(f"  {'-' * 90}")
        for r in results[:15]:
            isd, oos = r.get("in_sample", {}), r.get("oos", {})
            print(
                f"  {_params_label(r['params']):<40} "
                f"${isd.get('total_pnl', 0):>8.0f} "
                f"${oos.get('total_pnl', 0):>8.0f} "
                f"{oos.get('total_trades', 0):>6} "
                f"{oos.get('win_rate', 0):>6.1f}% "
                f"${oos.get('ev_per_trade', 0):>7.2f} "
                f"{oos.get('sharpe', 0):>7.3f}"
            )
    else:
        print(f"  {'Params':<40} {'Trades':>6} {'WinR%':>6} {'PnL':>10} "
              f"{'EV/T':>8} {'PF':>6} {'Sharpe':>7}")
        print(f"  {'-' * 90}")
        for r in results[:15]:
            print(
                f"  {_params_label(r['params']):<40} "
                f"{r.get('total_trades', 0):>6} "
                f"{r.get('win_rate', 0):>5.1f}% "
                f"${r.get('total_pnl', 0):>9.0f} "
                f"${r.get('ev_per_trade', 0):>7.2f} "
                f"{r.get('profit_factor', 0):>6.2f} "
                f"{r.get('sharpe', 0):>7.3f}"
            )
    print(f"{'=' * 92}\n")


def _print_recommendation(results: list[dict], objective: str) -> None:
    if not results:
        return

    best      = results[0]
    p         = best.get("params", {})
    validated = "oos" in best

    print("=" * 92)
    print("  RECOMMENDATION")
    print("=" * 92)
    print(f"\n  Best parameter set (max {'OOS ' if validated else ''}{objective}):")
    for k, v in p.items():
        cur = {
            "LONG_THRESHOLD": 60.0, "SHORT_THRESHOLD": 40.0,
            "ATR_STOP_MULTIPLE": 2.0, "ATR_TARGET_MULTIPLE": 4.0,
        }.get(k, "?")
        arrow = "↑" if float(v) > float(cur) else "↓" if float(v) < float(cur) else "="
        print(f"    {k:<26} {cur} → {v}  {arrow}")

    if validated:
        isd, oos = best.get("in_sample", {}), best.get("oos", {})
        is_pnl, oos_pnl = isd.get("total_pnl", 0), oos.get("total_pnl", 0)
        print(f"\n  In-sample (tune) : PnL=${is_pnl:.0f}  WinRate={isd.get('win_rate',0):.1f}%  "
              f"Trades={isd.get('total_trades',0)}")
        print(f"  Out-of-sample    : PnL=${oos_pnl:.0f}  WinRate={oos.get('win_rate',0):.1f}%  "
              f"EV/trade=${oos.get('ev_per_trade',0):.2f}  Sharpe={oos.get('sharpe',0):.2f}  "
              f"Trades={oos.get('total_trades',0)}")
        # Overfit check: OOS should stay positive and not collapse vs in-sample.
        if oos_pnl <= 0:
            print("\n  ⚠️  OOS profit is non-positive — these params do NOT generalise. "
                  "Do not deploy; lengthen --days or widen the grid.")
        elif is_pnl > 0 and oos_pnl < 0.4 * is_pnl:
            print("\n  ⚠️  OOS profit is far below in-sample — likely overfit. Treat with caution.")
        else:
            print("\n  ✅ OOS profit holds up vs in-sample — params generalise.")
    else:
        print(f"\n  Stats:  PnL=${best.get('total_pnl',0):.0f}  "
              f"EV/trade=${best.get('ev_per_trade',0):.2f}  "
              f"WinRate={best.get('win_rate',0):.1f}%  "
              f"PF={best.get('profit_factor',0):.2f}  Trades={best.get('total_trades',0)}")
        print("\n  ⚠️  No walk-forward validation (--no-validate) — risk of overfitting.")

    print("\n  To apply, add to Railway env vars (or .env):")
    for k, v in p.items():
        print(f"    {k}={v}")
    print("=" * 92 + "\n")


# ── Main ───────────────────────────────────────────────────────────────────────

async def run(
    tickers: list[str],
    days: int,
    phase: str,
    *,
    objective: str = "total_pnl",
    validate: bool = True,
    use_llm: bool = False,
) -> None:
    settings = load_settings()
    if not settings.alpaca_key_id or not settings.alpaca_secret:
        logger.error("ALPACA_API_KEY_ID and ALPACA_API_SECRET must be set in .env or environment")
        return

    # Log and surface real trade history so the optimizer learns from live results.
    _hist_trades = load_closed_trades()
    _hist_stats  = summarize(_hist_trades)
    print(format_block(_hist_stats))

    # Use live bias to pre-filter the threshold grid: if live history shows a
    # strong directional bias (≥20% win-rate gap), skip combos that contradict it.
    _live_bias = _hist_stats.get("bias", "neutral")

    agent_note = "ALL agents (Vision LLM ON)" if use_llm else "all non-LLM agents (Vision/Decision off)"
    mode_note  = f"walk-forward {int(SPLIT_FRAC*100)}/{int((1-SPLIT_FRAC)*100)} OOS" if validate else "full-window (NO validation)"
    print(f"\nOptimizer — {days}d window, {len(tickers)} tickers: {tickers}")
    print(f"Objective: {objective}  |  Validation: {mode_note}  |  Agents: {agent_note}")
    print(f"Phase: {phase}  |  Slippage: {SLIPPAGE_PCT*100:.3f}%  |  Live bias: {_live_bias}\n")

    bars_cache, spy_bars = await _fetch_all(tickers, days, settings.alpaca_key_id, settings.alpaca_secret)
    if not bars_cache:
        logger.error("No bars fetched — check API keys and market hours")
        return

    if validate:
        is_cache, oos_cache = _split_caches(bars_cache, SPLIT_FRAC)
        if not oos_cache:
            logger.warning("Not enough data per ticker to split — falling back to full-window. "
                           "Use a longer --days for walk-forward validation.")
            is_cache, oos_cache = bars_cache, None
    else:
        is_cache, oos_cache = bars_cache, None

    thresh_results: list[dict] = []
    atr_results:    list[dict] = []

    if phase in ("thresholds", "both"):
        combos = _threshold_combos(atr_stop=2.0, atr_target=4.0)
        # Prune combos that contradict a confirmed live directional bias:
        # - bias=long  → skip combos where LONG_THRESHOLD > 68 (too restrictive on LONGs)
        # - bias=short → skip combos where SHORT_THRESHOLD < 32 (too restrictive on SHORTs)
        if _live_bias == "long" and len(combos) > 1:
            pruned = [c for c in combos if c["LONG_THRESHOLD"] <= 68]
            if pruned:
                print(f"  [bias=long] Pruned threshold grid: {len(combos)} → {len(pruned)} combos (capped LONG_T at 68)")
                combos = pruned
        elif _live_bias == "short" and len(combos) > 1:
            pruned = [c for c in combos if c["SHORT_THRESHOLD"] >= 32]
            if pruned:
                print(f"  [bias=short] Pruned threshold grid: {len(combos)} → {len(pruned)} combos (floored SHORT_T at 32)")
                combos = pruned
        thresh_results = await _run_grid("Phase 1 — threshold grid", combos, tickers, spy_bars,
                                         objective=objective, use_llm=use_llm,
                                         is_cache=is_cache, oos_cache=oos_cache)
        _print_table(thresh_results, "Phase 1 — Threshold Grid", objective)

    best_long  = thresh_results[0]["params"]["LONG_THRESHOLD"]  if thresh_results else 60.0
    best_short = thresh_results[0]["params"]["SHORT_THRESHOLD"] if thresh_results else 40.0

    if phase in ("atr", "both"):
        combos = _atr_combos(long_thresh=best_long, short_thresh=best_short)
        atr_results = await _run_grid("Phase 2 — ATR grid", combos, tickers, spy_bars,
                                      objective=objective, use_llm=use_llm,
                                      is_cache=is_cache, oos_cache=oos_cache)
        _print_table(atr_results, "Phase 2 — ATR Grid", objective)

    best_overall = (atr_results or thresh_results or [{}])[0]
    _print_recommendation(atr_results or thresh_results, objective)
    _write_dashboard_files(best_overall, days, objective, oos_cache is not None)

    RESULTS_FILE.write_text(json.dumps({
        "run_at":          datetime.utcnow().isoformat(),
        "tickers":         tickers,
        "days":            days,
        "objective":       objective,
        "validation":      mode_note,
        # Full grids (not just top 10) so the dashboard heatmap shows every cell.
        "threshold_grid":  thresh_results,
        "atr_grid":        atr_results,
        "best":            best_overall,
    }, indent=2))
    print(f"Full results saved to {RESULTS_FILE}\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Trading strategy optimizer — maximises live trading profit")
    parser.add_argument("--days",    type=int, default=60,
                        help="Lookback window in days (default 60 — needs enough for a 70/30 split)")
    parser.add_argument("--tickers", nargs="+", default=DEFAULT_TICKERS,
                        help="Tickers to backtest")
    parser.add_argument("--phase",   choices=["thresholds", "atr", "both"],
                        default="both",
                        help="Which grid to search (default: both)")
    parser.add_argument("--objective", choices=OBJECTIVES, default="total_pnl",
                        help="Metric to maximise (default: total_pnl = raw trading profit)")
    parser.add_argument("--no-validate", action="store_true",
                        help="Disable walk-forward OOS validation (NOT recommended — overfits).")
    parser.add_argument("--use-llm", action="store_true",
                        help="Also run VisionAgent (LLM, slower + uses Gemini quota). "
                             "The Decision LLM stays off — it bypasses the thresholds being tuned.")
    args = parser.parse_args()
    asyncio.run(run(
        args.tickers, args.days, args.phase,
        objective=args.objective,
        validate=not args.no_validate,
        use_llm=args.use_llm,
    ))


if __name__ == "__main__":
    main()
