ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramChatId"      TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramToken"       TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramTokenAt"     TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramActivatedAt" TIMESTAMP(3);
